name: CI

on:
  push:
    branches: [master, main, fix/**, feature/**]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install toolchain components
        run: rustup component add clippy rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo test --all-features --verbose
